#!/usr/bin/env bash
# shellcheck disable=2016,2155

set -u

# host environment
: "${XDG_RUNTIME_DIR:="/run/user/$(id -u)"}"
: "${XDG_DATA_HOME:="${HOME}/.local/share"}"
: "${XDG_STATE_HOME:="${HOME}/.local/state"}"
: "${XDG_CACHE_HOME:="${HOME}/.cache"}"
: "${XDG_CONFIG_HOME:="${HOME}/.config"}"
: "${DBUS_SESSION_BUS_ADDRESS:="unix:path=${XDG_RUNTIME_DIR}/bus"}"

# sljail common environment
SLJAIL_SELF_NAME="$(basename "${0}")"
: "${SLJAIL_STATE_HOME:="${XDG_STATE_HOME}/sljail"}"
: "${SLJAIL_RUNTIME_DIR:="${XDG_RUNTIME_DIR}/sljail"}"
: "${SLJAIL_CACHE_HOME:="${XDG_CACHE_HOME}/sljail"}"
: "${SLJAIL_CONFIG_HOME:="${XDG_CONFIG_HOME}/sljail"}"
: "${SLJAIL_PATH:="${SLJAIL_CONFIG_HOME}:/usr/share/sljail"}"
SLJAIL_GCC_ARGS=(-Wall -Wextra -lseccomp)
SLJAIL_SELF_PID="${$}"
trap 'exit 1' USR1

# sljail instance environment
SLJAIL_INSTANCE_NAME=
SLJAIL_INSTANCE_HOME=
SLJAIL_INSTANCE_USER_HOME=
SLJAIL_INSTANCE_RUNTIME_DIR=

# would-be environment inside the sandbox
# (the normal names but prefixed with 'SANDBOX_')
SANDBOX_USER="${USER}"
SANDBOX_UID=1000
SANDBOX_GID=1000
SANDBOX_HOSTNAME="$(cat '/etc/hostname')"
SANDBOX_XDG_RUNTIME_DIR="/run/user/${SANDBOX_UID}"
SANDBOX_HOME="/home/${SANDBOX_USER}"
SANDBOX_XDG_DATA_HOME="${SANDBOX_HOME}/.local/share"
SANDBOX_XDG_STATE_HOME="${SANDBOX_HOME}/.local/state"
SANDBOX_XDG_CACHE_HOME="${SANDBOX_HOME}/.cache"
SANDBOX_XDG_CONFIG_HOME="${SANDBOX_HOME}/.config"
SANDBOX_DBUS_SESSION_BUS_ADDRESS="${SANDBOX_XDG_RUNTIME_DIR}/bus"

say() {
  printf '%s: %s\n' "${SLJAIL_SELF_NAME}" "${1}" >&2
}

usage() {
  printf >&2 'usage: %s [OPTIONS...] [--] COMMAND [ARGS...]\n' "${SLJAIL_SELF_NAME}"
  printf >&2 'flags:\n'
  printf >&2 '  --help         Print this help\n'
  printf >&2 '  --profile      Specify profile file\n'
  printf >&2 '  --name         Specify instance name\n'
}

# resolve a file from SLJAIL_PATH by name or use path to file
sjfile() {
  [ -f "${1}" ] && printf '%s' "${1}" && return
  for dir in $(printf '%s' "${SLJAIL_PATH}" | tr ':' '\n') ; do
    [ -f "${dir}/${1}" ] && printf '%s' "${dir}/${1}" && return
  done
  say "no such sljail file: ${1}" && kill -USR1 "${SLJAIL_SELF_PID}" >/dev/null
}

# add bubblewrap argument
# example:
#   arg symlink '/usr/lib' '/lib'      # symlink '/usr/lib' to '/lib' inside the sandbox
#   arg unshare-all                    # unshare all namespaces
arg() {
  local arg_name="${1}"
  shift
  # shellcheck disable=2206
  bwrap_args+=("--${arg_name}" ${@})
}

# repeat the arg with all the other args - for glob binds
# example:
#   arg2 ro-bind-try '/usr' '/etc'     # bind '/usr' to '/usr', and '/etc' to '/etc'
#   arg2 dev-bind-try '/dev/nvidia'*   # bind all /dev/nvidia* devices
arg2() {
  local arg_name="${1}"
  shift
  for bind_arg in "${@}"; do
    arg "${arg_name}" "${bind_arg}" "${bind_arg}"
  done
}

# change username and home directory inside of the sandbox
# shellcheck disable=2034
user() {
  SANDBOX_USER="${1}"
  SANDBOX_HOME="/home/${SANDBOX_USER}"
  SANDBOX_XDG_DATA_HOME="${SANDBOX_HOME}/.local/share"
  SANDBOX_XDG_STATE_HOME="${SANDBOX_HOME}/.local/state"
  SANDBOX_XDG_CACHE_HOME="${SANDBOX_HOME}/.cache"
  SANDBOX_XDG_CONFIG_HOME="${SANDBOX_HOME}/.config"
  arg dir "${SANDBOX_HOME}"
  arg setenv 'HOME' "/home/${SANDBOX_USER}"
  arg chdir "/home/${SANDBOX_USER}"
}

# bind procedurally generated data to a file inside of the sandbox
# example:
#   bind-data '/etc/resolv.conf' 'nameserver 10.0.2.3'
bind-data() {
  exec {fd}< <(printf '%s' "${2}")
  arg bind-data "${fd}" "${1}"
}

# spoof machine-id
# argument should be 32-digit lowercase hex number
# if no arguments supplied, random id is generated for you
machine-id() {
  local machine_id="${1:-"$(tr -dc '[:digit:]abcdef' <'/dev/urandom'  | head -c 32)"}"
  bind-data '/etc/machine-id' "$(printf '%s\x0a' "${machine_id}")"
  arg symlink '/etc/machine-id' '/var/lib/dbus/machine-id'
}

# spoof /etc/passwd file
passwd() {
  local passwd="$(
    cat <<EOF
root:x:0:0::/root:/bin/bash
${SANDBOX_USER}:x:${SANDBOX_UID}:${SANDBOX_GID}::${SANDBOX_HOME}:/bin/sh
nobody:x:65534:65534:Nobody:/:/usr/bin/nologin
EOF
  )"
  bind-data '/etc/passwd' "${passwd}"
}

# spoof /etc/group file
group() {
  local group="$(
    cat <<EOF
root:x:0:root
${SANDBOX_USER}:x:${SANDBOX_GID}:${SANDBOX_USER}
nobody:x:65534:
EOF
  )"
  bind-data '/etc/group' "${group}"
}

# set localtime
# example:
#   localtime '/usr/share/zoneinfo/Turkey'
localtime() {
  exec {fd}<"${1}"
  arg bind-data "${fd}" '/etc/localtime'
}

# set hostname
# example:
#   hostname 'sandboxed-pc'
hostname() {
  SANDBOX_HOSTNAME="${1}"
  bind-data '/etc/hostname' "${SANDBOX_HOSTNAME}"
}

# spoof /etc/hosts file
hosts() {
  local hosts="$(
    cat <<EOF
127.0.0.1	localhost
::1		localhost
127.0.0.1	${SANDBOX_HOSTNAME}.localdomain	${SANDBOX_HOSTNAME}
EOF
  )"
  bind-data '/etc/hosts' "${hosts}"
}

# spoof /etc/host.conf file
host.conf() {
  local host_conf="$(
    cat <<EOF
multi on
EOF
  )"
  bind-data '/etc/host.conf' "${host_conf}"
}

# spoof /etc/nsswitch.conf file
nsswitch.conf() {
  local nsswitch_conf="$(
    cat <<EOF
passwd: files
group: files
shadow: files

publickey: files

hosts: files myhostname dns
networks: files

protocols: files
services: files
ethers: files
rpc: files

netgroup: files
EOF
  )"
  bind-data '/etc/nsswitch.conf' "${nsswitch_conf}"
}

dbus-system() {
  arg bind "${XDG_RUNTIME_DIR}/sljail/${SLJAIL_INSTANCE_NAME}/dbus_system_proxy" '/run/dbus/system_bus_socket'
  enable_dbus_system=true
}

dbus-user() {
  arg setenv 'DBUS_SESSION_BUS_ADDRESS' "${DBUS_SESSION_BUS_ADDRESS}"
  # FIXME: hardcoded dbus path
  arg bind "${XDG_RUNTIME_DIR}/sljail/${SLJAIL_INSTANCE_NAME}/dbus_session_proxy" "${SANDBOX_DBUS_SESSION_BUS_ADDRESS}"
  enable_dbus_user=true
}

# add a xdg-dbus-proxy policy as per it's manpage.
# example:
#   dbus-user.talk "org.freedesktop.Notifications"
dbus-user.own() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-user.talk() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-user.see() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-user.call() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-user.broadcast() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-user.log() { [ "${enable_dbus_user-}" != true ] && say "ERROR: you can't have dbus-user rules without dbus-user enabled" && exit 1; dbus_user_args+=(--log); }

dbus-system.own() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-system.talk() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-system.see() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-system.call() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-system.broadcast() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=("--${FUNCNAME#*.}=${1}"); }
dbus-system.log() { [ "${enable_dbus_system-}" != true ] && say "ERROR: you can't have dbus-system rules without dbus-system enabled" && exit 1; dbus_system_args+=(--log); }

# enable private networking stack
# requires 'slirp4netns' and 'rootlesskit' binaries present in PATH.
# NOTE/FIXME: this also has a sideeffect of piping stderr of the program to stdout
slirp4netns() {
  enable_slirp4netns=true
}

# use precompiled bpf file as a seccomp-bpf filter of the sandbox
seccomp-precompiled() {
  exec {fd}<"${1}"
  arg seccomp "${fd}"
}

# use a C source file that exports seccomp-bpf filter to stdout as a
# seccomp-bpf filter of the sandbox.
# this function also caches already compiled binaries and bpfs that they
# export.
seccomp() {
  local seccomp_profile="${1}" # /home/pr/sljail/seccomp/default.c
  local seccomp_profile_name="$(basename "${seccomp_profile}")" # default.c
  local seccomp_profile_name="${seccomp_profile_name%.c}" # default
  local binary="${SLJAIL_CACHE_HOME}/seccomp/$(sha256sum "${seccomp_profile}" | cut -d' ' -f1)-${seccomp_profile_name}" # /home/.cache/sljail/seccomp/aabbccddeeff001122334455-default
  if ! [ -f "${binary}" ]; then
    mkdir -p "$(dirname "${binary}")"
    gcc "${SLJAIL_GCC_ARGS[@]}" -o "${binary}" "${seccomp_profile}"
    "${binary}" >"${binary}.bpf"
  fi
  exec {fd}<"${binary}.bpf"
  arg seccomp "${fd}"
}

# set the name of this instance. will influence things like it's runtime dir and state dir (home jail), etc.
# shellcheck disable=2034
name() {
  SLJAIL_INSTANCE_NAME="${1}"
  SLJAIL_INSTANCE_HOME="${SLJAIL_STATE_HOME}/${SLJAIL_INSTANCE_NAME}"
  SLJAIL_INSTANCE_USER_HOME="${SLJAIL_INSTANCE_HOME}/home"
  SLJAIL_INSTANCE_RUNTIME_DIR="${SLJAIL_RUNTIME_DIR}/${SLJAIL_INSTANCE_NAME}"
}

# parse arguments
profile=
while :; do
  case "${1-}" in
    -h | -\? | --help) # call a "usage" function to display a synopsis, then exit.
      usage
      exit
      ;;
    -p | --profile) # get profile file and continue.
      profile="$(sjfile "${2-}")"
      shift
      [ -z "${profile}" ] && say 'ERROR: `--profile` requires a non-empty option argument.' && exit 1
      ;;
    -n | --name)
      [ -z "${2-}" ] && say 'ERROR: `--name` requires a non-empty option argument.' && exit 1
      name "${2-}"
      shift
      ;;
    --) # break option parsing, treat everything as positional arguments after it.
      shift
      break
      ;;
    -?*) # unknown option
      say "ERROR: unknown option: ${1}"
      ;;
    *) # default case: if no more options then break out of the loop.
      break ;;
  esac
  shift
done

# validate arguments
[ -z "${profile}" ] && say 'ERROR: `--profile` is required.' && exit 1
[ -z "${SLJAIL_INSTANCE_NAME}" ] && say 'ERROR: sljail instance is required to have a name. Either pass it through the `--name` argument, or specify it in the profile with the `name` command.' && exit 1

# initialize args arrays
bwrap_args=()
dbus_system_args=()
dbus_user_args=()

################################################################################

# source the profile
# shellcheck disable=1090
source "${profile}"

################################################################################

# positional arguments
[ -z "${1-}" ] && say 'ERROR: `COMMAND` is required' && usage && exit 1
program="${1}" && shift

# start xdg dbus proxy if enabled
if [ -z "${DEBUG-}" ] && { [ "${enable_dbus_system-}" = true ] || [ "${enable_dbus_user-}" = true ]; }; then
  # setup args for xdg dbus proxy
  pipe="$(mktemp -u)"
  mkfifo "${pipe}"
  exec {xdg_dbus_proxy_fd}<>"${pipe}"
  rm "${pipe}"
  xdg_dbus_proxy_args=(
    --fd="${xdg_dbus_proxy_fd}"
  )
  [ "${enable_dbus_system}" = true ] && xdg_dbus_proxy_args+=(
    'unix:path=/run/dbus/system_bus_socket'
    "${SLJAIL_INSTANCE_RUNTIME_DIR}/dbus_system_proxy"
    --filter "${dbus_system_args[@]}"
  )
  [ "${enable_dbus_user}" = true ] && xdg_dbus_proxy_args+=(
    "${DBUS_SESSION_BUS_ADDRESS}"
    "${SLJAIL_INSTANCE_RUNTIME_DIR}/dbus_session_proxy"
    --filter "${dbus_user_args[@]}"
  )

  mkdir -p "${SLJAIL_INSTANCE_RUNTIME_DIR}"
  xdg-dbus-proxy "${xdg_dbus_proxy_args[@]}" &
  xdg_dbus_proxy_pid="${!}"
  cleanup_sljail_runtime_dir() { kill "${xdg_dbus_proxy_pid}"; }

  # wait for proxies
  read -N 1 -r -u "${xdg_dbus_proxy_fd}" _
fi

# debug mode: only print args and exit
if [ -n "${DEBUG-}" ]; then
  # shellcheck disable=2001
  echo "${bwrap_args[@]}" | sed 's/--/\n--/g' >&2
  echo "${program}" "${@}" >&2
fi

# DANGER: rm -rf of dynamic value. nothing bad happens, right?
# shellcheck disable=2064
cleanup_xdg_dbus_proxy() { rm -rf "${SLJAIL_INSTANCE_RUNTIME_DIR}"; }

# can have only one trap for each signal, so:
exit_traps() {
  cleanup_xdg_dbus_proxy
  cleanup_sljail_runtime_dir
}
trap exit_traps EXIT TERM HUP

# start with slirp4netns if enabled
if [ "${enable_slirp4netns-}" = true ]; then
  rootlesskit 2>&1 \
    --net='slirp4netns' \
    --disable-host-loopback \
    --slirp4netns-sandbox true \
    --slirp4netns-seccomp true \
    --mtu 65520 \
    --cidr '10.0.2.0/24' \
    --copy-up='/etc' \
      bwrap "${bwrap_args[@]}" -- "${program}" "${@}"  |
    grep -v '\[rootlesskit:'
  exit
fi

# or start normally
bwrap "${bwrap_args[@]}" -- "${program}" "${@}"
